"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Drawer from "./components/Drawer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [drawerOpen, setDrawerOpen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-black">
          <Drawer drawerOpen={drawerOpen} setDrawerOpen={setDrawerOpen} />
          <div>
            <Navbar drawerOpen={drawerOpen} setDrawerOpen={setDrawerOpen} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
